---
name: Tests - msgraph
on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "msgraph/**.go"
      - ".github/workflows/msgraph-tests.yml"

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test-msgraph:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: go test -count=1 -race -v ./msgraph
#        env:
#          AZURE_ENVIRONMENT: ${{ secrets.AZURE_ENVIRONMENT }}
#          CLIENT_ID: ${{ secrets.CLIENT_ID }}
#          TENANT_ID: ${{ secrets.TENANT_ID }}
#          TENANT_DOMAIN: ${{ secrets.TENANT_DOMAIN }}

# vim: set ts=2 sts=2 sw=2 et:
